### ISSUE TITLE
README

### ISSUE THREAD

**Issue by misterblonde** [dgleich/gaimc#4]
Hi David,

I really would like to try your library. It looks really good and I saw it being used in other contexts already. I'm not an extensive MATLAB user and I regret that your gaimc doesn't even come with a README file to clarify how it needs to be installed. 

If I run gsp_install.m, it just throws an error regarding gsp_start...

Thanks

Julia

**Comment by dgleich** [comment]
gsp_install isn't my function ... you just put this into a directory on your path -- there is no need to install anything.

**Comment by misterblonde** [comment]
Thanks a lot for the quick reply! The other code that suggested to use yours said "download and install" 😄 thanks again.
